config/routes.rb
Rails.application.routes.draw do
  get 'spot_pages/night'
  get 'spot_pages/dinner'
  get 'users/new'

  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
   }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  get 'pages/index'
  get 'pages/show'
  get 'pages/home'
  get 'pages/help'
  get 'pages/about'

  get 'users/show'
  get 'users/index'

  get 'posts/new'
  get 'posts/index'

  get 'posts/night'
  get 'posts/dinner'
  get 'posts/cafe'
  get 'posts/sweets'
  get 'posts/nature'
  get 'posts/themepark'

  get 'tags/:tag', to: 'posts#index', as: :tag #追加

  get "posts/show/:id" => "posts#show"
  delete 'posts/show/:id' => 'posts#destroy'

  get 'users/show/:id' => 'users#show'

  root "pages#home"

  resources :posts,          only: [:create, :show, :destroy] do
    resources :likes, only: [:create, :destroy]
  end

  resources :posts do
    resources :comments, only: [:create, :destroy]
  end

  resources :users do
    member do
     get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  attachment :image
  acts_as_taggable

  TAG_TYPES = {
    'night' => '夜景',
    'cafe' =>   'カフェ',
    'sweets' => 'スイーツ',
    'dinner' => 'ディナー',
    'theme' =>  'テーマパーク',
    'shopping' => '自然'
  }

  validates :image, presence: true
  validates :title, presence: true, length: { maximum: 15 }
  validates :body, presence: true, length: { maximum: 1000 }
  validates :tag_list, presence: true

  acts_as_taggable_on \
    :tag_types

  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user

  has_many :comments, dependent: :destroy

  paginates_per 12
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: %i[show cafe night sweets dinner themepark nature index]
  before_action :login_required, only: [:new]
  def new
    @post = Post.new
  end

  def show
    @like = Like.new
    @post = Post.find_by(id: params[:id])
    @posts = Post.find_by(params[:id])
    @user = User.find_by(id: @posts.user_id)
    @comments = @post.comments.includes(:user).all
    @comment = @post.comments.build(user_id: current_user.id) if current_user
    @commentss = @post.comments.build
  end

  def destroy
    @post = Post.find_by(id: params[:id])
    @post.destroy
    redirect_to root_path
  end

  def index
    @post = Post.all
    @posts = Post.find_by(params[:id])
    @user = User.find_by(id: @posts.user_id)
    @items = Post.page(params[:page]).per(12)
    if params[:tag]
      @users = User.tagged_with(params[:tag])
    else
      @users = User.all
    end
  end

  def night
    @spot = Post.tagged_with('night')
    @post = Post.all
    @posts = Post.find_by(params[:id])
    @user = User.find_by(id: @posts.user_id)
  end

  def cafe
    @spot = Post.tagged_with('cafe')
    @post = Post.all
    @posts = Post.find_by(params[:id])
    @user = User.find_by(id: @posts.user_id)
  end

  def sweets
    @spot = Post.tagged_with('sweets')
    @post = Post.all
    @posts = Post.find_by(params[:id])
    @user = User.find_by(id: @posts.user_id)
  end

  def dinner
    @spot = Post.tagged_with('dinner')
    @post = Post.all
    @posts = Post.find_by(params[:id])
    @user = User.find_by(id: @posts.user_id)
  end

  def themepark
    @spot = Post.tagged_with('theme')
    @post = Post.all
    @posts = Post.find_by(params[:id])
    @user = User.find_by(id: @posts.user_id)
  end

  def nature
    @spot = Post.tagged_with('shopping')
    @post = Post.all
    @posts = Post.find_by(params[:id])
    @user = User.find_by(id: @posts.user_id)
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to root_path, notice: '投稿しました'
    elsif @post.title.empty?
      render 'new',
      alert: '施設名を入力してください'
        elsif @post.body.empty?
          render 'new',
          alert: '内容を入力してください'
            elsif @post.tag_list.empty?
              render 'new',
              alert: 'タグを選択してください'
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :image, :content, :tag_list)
  end

  def login_required
    redirect_to login_path unless current_user
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_like.html.erb
<% if user_signed_in? %>
<h3>いいね件数: <%= @post.likes.count %></h3>
<% if current_user.already_liked?(@post) %>
  <%= button_to 'いいねを取り消す', post_like_path(@post), method: :delete %>
<% else %>
  <%= button_to 'いいね', post_likes_path(@post) %>
<% end %>
<% else %>
<h3>いいね件数: <%= @post.likes.count %></h3>
<% end %>

<h2>いいねしたユーザー</h2>
<% @post.liked_users.each do |user| %>
  <li><%= user.email %></li>
<% end %>

app/views/posts/_like_form.html.erb
<% if user_signed_in? %>
  <% if current_user.already_liked?(@post) %>
  <div class="unlike-btn">
        <%= link_to post_like_path(@post), method: :delete, class: "unlike-btn btn", onfocus: "this.blur();"  do %>
        <p>いいね！済み</p>
        <% end %></div>

  <% else %>
  <div class="like-btn">
        <%= link_to post_likes_path(@post), method: :post, class: "btn like-btn", onfocus: "this.blur();" do %>
        <p>いいね！<i class="far fa-thumbs-up"></i></p>

  <% end %></div>
<% end %>
<% else %>
  <div class="good-btn">
    <p>いいね！<i class="far fa-thumbs-up"></i><%= @post.likes.count %></p>
  </div>
<% end %>

app/views/posts/_show_comment.html.erb
<div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
  <% if @comments.present? %>
    <% @comments.each do |comment| %>
      <div class="comment d-flex">
      <div class="comment-avatar">
        <% if comment.user.avatar_id? %>
          <%=link_to (image_tag attachment_url(comment.user, :avatar, :fill, 50, 50, format: "jpg")), user_path(comment.user) %>
        <% else %>
          <%=link_to (image_tag('/images/user-default.png',size: '50x50')), user_path(comment.user) %>
        <% end %>
      </div>

      <div class="comment-body">
        <div class="comment-author">
          <%= link_to "@#{comment.user.username}", user_path(comment.user), class: "author-username", style: "color:black;" %>
        </div>
        <div class="comment-text"><%= comment.content %></div>
        <div class="time-agooo d-flex">
          <div class="time-agoo">
        <%= time_ago_in_words(comment.created_at) %>前
        </div>
        <% if user_signed_in? %>
          <% if comment.user_id == current_user.id %>
          <div class="delete">
            <%= link_to '削除', post_comment_path(comment.post.id, comment.id), method: :delete, data: { confirm: "コメントを削除しますか？この操作は取り消せません。"}, class: "btn" %>
          </div>
          <% end %>
          <% end %>
        </div>
      </div>
    </div>
    <% end %>
  <% else %>
    <div class="no-contents d-flex align-items-center justify-content-center mx-auto">
      まだコメントがありません
    </div>
  <% end %>

  <% if user_signed_in? %>
    <%= form_for [@post, @comment] do |f| %>
      <div class="comment-boxx">
        <div class="comment-box">
          <%= f.text_area :content, rows:4,class: "form-control", placeholder: "コメントを記入..." %>
        </div>
        </div>
        <div class="comment-btn">
      <%= f.submit "コメントを送信", { class: "btn", style: "background-color: white;" } %>
      </div>
    <% end %>
  <% end %>

app/views/posts/_show_liked.html.erb
<% if @post.likes.present? %>
  <div class="users-index">
    <div class="container">
      <div class="user-item-box">
        <div class="post-cardss latest row">
          <% @post.liked_users.each do |user| %>
            <div class="user-cards d-flex align-items-center col-6 col-sm-4">
              <div style="width: 100%" >
                <div class="user-item user-list">
                  <% if user.avatar_id.present? %>
                    <%=link_to (image_tag attachment_url(user, :avatar, :fill, 110, 110, format: "jpg")),"/users/show/#{user.id}", class: 'user-img' %>
                  <% else %>
                    <%=link_to (image_tag('/images/user-default.png', size: '110x110', class: 'user-img')), "/users/show/#{user.id}" %>
                  <% end %>
                </div>
                <br>
                <div class="user-name">
                  <%= user.username %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% else %>
<div class="no-contents d-flex align-items-center justify-content-center mx-auto">
  いいね！はまだされていません
  </div>
<% end %>

app/views/posts/_tag_list.html.erb
<% tag_list.each do |tag| %>
  <span class="badge badge-primary"><%= tag %></span>
<% end %>

app/views/posts/cafe.html.erb
<div class="all-user">
<a class="text-center">投稿一覧</a>
</div>
<div class="post-cardsx row">
  <% @spot.each do |post| %>
    <div class="post-cardssss col-6 col-sm-4">
      <div class="post-card-imgss">
        <% if post.image_id.present? %>
          <%=link_to (image_tag attachment_url(post, :image, :fill, 300, 260,  format: "jpg")), "/posts/show/#{post.id}", class: 'post-photoss img-fluid', alt:"post image" %>
        <% end %>
      </div>
      <div class="post-user">
        <% if post.user.avatar_id.present? %>
          <%=link_to (image_tag attachment_url(post.user, :avatar, :fill, 50, 50, format: "jpg")), user_path(post.user) %>
        <% else %>
          <%=link_to (image_tag('/images/user-default.png',size: '50x50')), user_path(post.user) %>
        <% end %>
      </div>
        <div class="post-footer-namess" style="line-height: 20px;">
          <%= link_to "@#{post.user.username}", user_path(post.user), class: "post-footer-username" %></a>
          <% if user_signed_in? %>
            <% if current_user.already_liked?(post) %>
              <i class="fas fa-heart unlike-btn"></i>
            <% else %>
              <i class="far fa-heart like-btn" ></i>
            <% end %>
            <%= post.likes.count %>
          <% else %>
            <i class="far fa-heart like-btn" ></i>
            <%= post.likes.count %>
          <% end %>
          <i class="fas fa-comments"></i></i> <%= post.comments.count %>
            <br>
          <div class="post-time">
            <%= time_ago_in_words(post.created_at) %>前
          </div>
        </div>
      </div>
  <% end %>
</div>

app/views/posts/dinner.html.erb
<div class="all-user">
<a class="text-center">投稿一覧</a>
</div>
<div class="post-cardsx row">
  <% @spot.each do |post| %>
    <div class="post-cardssss col-6 col-sm-4">
      <div class="post-card-imgss">
        <% if post.image_id.present? %>
          <%=link_to (image_tag attachment_url(post, :image, :fill, 300, 260,  format: "jpg")), "/posts/show/#{post.id}", class: 'post-photoss img-fluid', alt:"post image" %>
        <% end %>
      </div>
      <div class="post-user">
        <% if post.user.avatar_id.present? %>
          <%=link_to (image_tag attachment_url(post.user, :avatar, :fill, 50, 50, format: "jpg")), user_path(post.user) %>
        <% else %>
          <%=link_to (image_tag('/images/user-default.png',size: '50x50')), user_path(post.user) %>
        <% end %>
      </div>
        <div class="post-footer-namess" style="line-height: 20px;">
          <%= link_to "@#{post.user.username}", user_path(post.user), class: "post-footer-username" %></a>
          <% if user_signed_in? %>
            <% if current_user.already_liked?(post) %>
              <i class="fas fa-heart unlike-btn"></i>
            <% else %>
              <i class="far fa-heart like-btn" ></i>
            <% end %>
            <%= post.likes.count %>
          <% else %>
            <i class="far fa-heart like-btn" ></i>
            <%= post.likes.count %>
          <% end %>
          <i class="fas fa-comments"></i></i> <%= post.comments.count %>
            <br>
          <div class="post-time">
            <%= time_ago_in_words(post.created_at) %>前
          </div>
        </div>
      </div>
  <% end %>
</div>

app/views/posts/index.html.erb
<div class="all-user">
<a class="text-center">投稿一覧</a>
</div>
<div class="post-cardsx row">
  <% @post.each do |post| %>
    <div class="post-cardssss col-6 col-sm-4">
      <div class="post-card-imgss">
        <% if post.image_id.present? %>
          <%=link_to (image_tag attachment_url(post, :image, :fill, 300, 260,  format: "jpg")), "/posts/show/#{post.id}", class: 'post-photoss img-fluid', alt:"post image" %>
        <% end %>
      </div>
      <div class="post-user">
        <% if post.user.avatar_id.present? %>
          <%=link_to (image_tag attachment_url(post.user, :avatar, :fill, 50, 50, format: "jpg")), user_path(post.user) %>
        <% else %>
          <%=link_to (image_tag('/images/user-default.png',size: '50x50')), user_path(post.user) %>
        <% end %>
      </div>
        <div class="post-footer-namess" style="line-height: 20px;">
          <%= link_to "@#{post.user.username}", user_path(post.user), class: "post-footer-username" %></a>
          <% if user_signed_in? %>
            <% if current_user.already_liked?(post) %>
              <i class="fas fa-heart unlike-btn"></i>
            <% else %>
              <i class="far fa-heart like-btn" ></i>
            <% end %>
            <%= post.likes.count %>
          <% else %>
            <i class="far fa-heart like-btn" ></i>
            <%= post.likes.count %>
          <% end %>
          <i class="fas fa-comments"></i></i> <%= post.comments.count %>
            <br>
          <div class="post-time">
            <%= time_ago_in_words(post.created_at) %>前
          </div>
        </div>
      </div>
  <% end %>
</div>

app/views/posts/nature.html.erb
<div class="all-user">
<a class="text-center">投稿一覧</a>
</div>
<div class="post-cardsx row">
  <% @spot.each do |post| %>
    <div class="post-cardssss col-6 col-sm-4">
      <div class="post-card-imgss">
        <% if post.image_id.present? %>
          <%=link_to (image_tag attachment_url(post, :image, :fill, 300, 260,  format: "jpg")), "/posts/show/#{post.id}", class: 'post-photoss img-fluid', alt:"post image" %>
        <% end %>
      </div>
      <div class="post-user">
        <% if post.user.avatar_id.present? %>
          <%=link_to (image_tag attachment_url(post.user, :avatar, :fill, 50, 50, format: "jpg")), user_path(post.user) %>
        <% else %>
          <%=link_to (image_tag('/images/user-default.png',size: '50x50')), user_path(post.user) %>
        <% end %>
      </div>
        <div class="post-footer-namess" style="line-height: 20px;">
          <%= link_to "@#{post.user.username}", user_path(post.user), class: "post-footer-username" %></a>
          <% if user_signed_in? %>
            <% if current_user.already_liked?(post) %>
              <i class="fas fa-heart unlike-btn"></i>
            <% else %>
              <i class="far fa-heart like-btn" ></i>
            <% end %>
            <%= post.likes.count %>
          <% else %>
            <i class="far fa-heart like-btn" ></i>
            <%= post.likes.count %>
          <% end %>
          <i class="fas fa-comments"></i></i> <%= post.comments.count %>
            <br>
          <div class="post-time">
            <%= time_ago_in_words(post.created_at) %>前
          </div>
        </div>
      </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="container">
<div class="all-user">
<a class="text-center">投稿する</a>
</div>
<%= form_for (@post) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
<div class="post-form">
    <div class="preview-wrap" onClick="$('#file').click()">
      <div id="img_field">

      </div>
      <i class="fas fa-camera" onClick="$('#file').click()"></i>
    </div>
      <%= f.file_field :image, class: "image", style: "display: none;", id: "file", accept: 'image/jpeg,image/gif,image/png' %>
</div>




  <div class="field">
    <%= f.text_area :title, autofocus: true, rows:1, class: "form-control", placeholder: "施設名を記入..."  %>
    <%= f.text_area :body, rows:8,class: "form-control", placeholder: "内容を記入..." %>
  </div>

 <div class="form-group">
    <div class="cp_ipselect cp_sl06">
    <%= f.select :tag_list, Post::TAG_TYPES.map { |key, value| [value, key] }, include_blank: 'タグ選択', class: "cp_ipselect cp_sl06" %>
  </div>
  </div>




<div class="post-form-btns text-right mb-4">
    <%= link_to "キャンセル", root_path, class: "btn post-form-btn mr-2", style: "border: none;" %>
    <%= f.submit "投稿を送信", { class: "btn post-form-btn mr-3", style: "background-color: white;" } %>
  </div>
<% end %>




<!--　画像プレビュー(パーシャルにする) -->
<script type="text/javascript">



  <!--　テスト -->
$(function(){
    $fileField = $('#file')

    // 選択された画像を取得し表示
    $($fileField).on('change', $fileField, function(e) {
      file = e.target.files[0]
      reader = new FileReader(),
      $preview = $("#img_field");

      reader.onload = (function(file) {
        return function(e) {
          $preview.empty();
          $preview.append($('<img>').attr({
            src: e.target.result,
            width: "100%",
            class: "preview",
            title: file.name
          }));
        };
      })(file);
      reader.readAsDataURL(file);
    });
  });
  <!-- /テスト -->
</script>

app/views/posts/night.html.erb
<div class="all-user">
<a class="text-center">投稿一覧</a>
</div>
<div class="post-cardsx row">
  <% @spot.each do |post| %>
    <div class="post-cardssss col-6 col-sm-4">
      <div class="post-card-imgss">
        <% if post.image_id.present? %>
          <%=link_to (image_tag attachment_url(post, :image, :fill, 300, 260,  format: "jpg")), "/posts/show/#{post.id}", class: 'post-photoss img-fluid', alt:"post image" %>
        <% end %>
      </div>
      <div class="post-user">
        <% if post.user.avatar_id.present? %>
          <%=link_to (image_tag attachment_url(post.user, :avatar, :fill, 50, 50, format: "jpg")), user_path(post.user) %>
        <% else %>
          <%=link_to (image_tag('/images/user-default.png',size: '50x50')), user_path(post.user) %>
        <% end %>
      </div>
        <div class="post-footer-namess" style="line-height: 20px;">
          <%= link_to "@#{post.user.username}", user_path(post.user), class: "post-footer-username" %></a>
          <% if user_signed_in? %>
            <% if current_user.already_liked?(post) %>
              <i class="fas fa-heart unlike-btn"></i>
            <% else %>
              <i class="far fa-heart like-btn" ></i>
            <% end %>
            <%= post.likes.count %>
          <% else %>
            <i class="far fa-heart like-btn" ></i>
            <%= post.likes.count %>
          <% end %>
          <i class="fas fa-comments"></i></i> <%= post.comments.count %>
            <br>
          <div class="post-time">
            <%= time_ago_in_words(post.created_at) %>前
          </div>
        </div>
      </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="post-show">
  <div class="post-header">
    <div class="post-userr">
      <% if @post.user.avatar_id.present? %>
        <%=link_to (image_tag attachment_url(@post.user, :avatar, :fill, 60, 60, format: "jpg")), user_path(@post.user) %>
      <% else %>
        <%=link_to (image_tag('/images/user-default.png',size: '60x60')), user_path(@post.user) %>
      <% end %>
      <%= link_to "@#{@post.user.username}", user_path(@post.user), class: "post-footer-username", style: "color:black;" %></a>
    </div>
    <div class="like-form">
      <%= render 'posts/like_form'%>
    </div>
  </div>

  <div class="post-image">
    <% if @post.image_id.present? %>
      <%= image_tag attachment_url(@post, :image, :fill, 600, 600, format: "jpg"), class: "img-fluid" %>
    <% else %>
      <%= image_tag('/images/post-default.jpg', size: '600x600', class: "img-fluid") %>
    <% end %>
  </div>
<div class="post-sentece">
  <div class="post-infoo">
    <div class="post-titlee">
      <%= @post.title %>
    </div>
    <div class="post-bodyy">
      <%= @post.body %>
    </div>
    <div class="time-ago d-flex">
      <%= time_ago_in_words(@posts.created_at) %>前
      <% if user_signed_in? %>
        <% if @post.user_id == current_user.id %>
        <%= link_to "削除", post_path, method: :delete, class: "btn", data: { confirm: "投稿を削除しますか？この操作は取り消せません。"}%>
      <% end %>
      <% end %>
    </div>
  </div>
<!-- navテスト -->

<!-- pills -->

<!-- コメント -->
<div class="user-status-cell">
  <div class="post-footer">
    <ul class="nav nav-pills justify-content-around justify-content-md-center" id="pills-tab" role="tablist">
      <li class="nav-item">
        <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">コメント<%= @comments.count.to_s(:delimited) %></a>
      </li>
      <li class="nav-item">
<!-- いいね -->
      <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">いいね<%= @post.likes.count.to_s(:delimited) %></a>
      </li>
    </ul>

    <div class="tab-content" id="myTabContent" style="width: 100%">
      <%= render 'show_comment' %>
    </div>

    <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
      <%= render 'show_liked' %>
    </div>

  </div>
</div>
</div>
</div>

app/views/posts/sweets.html.erb
<div class="all-user">
<a class="text-center">投稿一覧</a>
</div>
<div class="post-cardsx row">
  <% @spot.each do |post| %>
    <div class="post-cardssss col-6 col-sm-4">
      <div class="post-card-imgss">
        <% if post.image_id.present? %>
          <%=link_to (image_tag attachment_url(post, :image, :fill, 300, 260,  format: "jpg")), "/posts/show/#{post.id}", class: 'post-photoss img-fluid', alt:"post image" %>
        <% end %>
      </div>
      <div class="post-user">
        <% if post.user.avatar_id.present? %>
          <%=link_to (image_tag attachment_url(post.user, :avatar, :fill, 50, 50, format: "jpg")), user_path(post.user) %>
        <% else %>
          <%=link_to (image_tag('/images/user-default.png',size: '50x50')), user_path(post.user) %>
        <% end %>
      </div>
        <div class="post-footer-namess" style="line-height: 20px;">
          <%= link_to "@#{post.user.username}", user_path(post.user), class: "post-footer-username" %></a>
          <% if user_signed_in? %>
            <% if current_user.already_liked?(post) %>
              <i class="fas fa-heart unlike-btn"></i>
            <% else %>
              <i class="far fa-heart like-btn" ></i>
            <% end %>
            <%= post.likes.count %>
          <% else %>
            <i class="far fa-heart like-btn" ></i>
            <%= post.likes.count %>
          <% end %>
          <i class="fas fa-comments"></i></i> <%= post.comments.count %>
            <br>
          <div class="post-time">
            <%= time_ago_in_words(post.created_at) %>前
          </div>
        </div>
      </div>
  <% end %>
</div>

app/views/posts/themepark.html.erb
<div class="all-user">
<a class="text-center">投稿一覧</a>
</div>
<div class="post-cardsx row">
  <% @spot.each do |post| %>
    <div class="post-cardssss col-6 col-sm-4">
      <div class="post-card-imgss">
        <% if post.image_id.present? %>
          <%=link_to (image_tag attachment_url(post, :image, :fill, 300, 260,  format: "jpg")), "/posts/show/#{post.id}", class: 'post-photoss img-fluid', alt:"post image" %>
        <% end %>
      </div>
      <div class="post-user">
        <% if post.user.avatar_id.present? %>
          <%=link_to (image_tag attachment_url(post.user, :avatar, :fill, 50, 50, format: "jpg")), user_path(post.user) %>
        <% else %>
          <%=link_to (image_tag('/images/user-default.png',size: '50x50')), user_path(post.user) %>
        <% end %>
      </div>
        <div class="post-footer-namess" style="line-height: 20px;">
          <%= link_to "@#{post.user.username}", user_path(post.user), class: "post-footer-username" %></a>
          <% if user_signed_in? %>
            <% if current_user.already_liked?(post) %>
              <i class="fas fa-heart unlike-btn"></i>
            <% else %>
              <i class="far fa-heart like-btn" ></i>
            <% end %>
            <%= post.likes.count %>
          <% else %>
            <i class="far fa-heart like-btn" ></i>
            <%= post.likes.count %>
          <% end %>
          <i class="fas fa-comments"></i></i> <%= post.comments.count %>
            <br>
          <div class="post-time">
            <%= time_ago_in_words(post.created_at) %>前
          </div>
        </div>
      </div>
  <% end %>
</div>