config/routes.rb
Rails.application.routes.draw do
  get 'spot_pages/night'
  get 'spot_pages/dinner'
  get 'users/new'

  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
   }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  get 'pages/index'
  get 'pages/show'
  get 'pages/home'
  get 'pages/help'
  get 'pages/about'

  get 'users/show'
  get 'users/index'

  get 'posts/new'
  get 'posts/index'

  get 'posts/night'
  get 'posts/dinner'
  get 'posts/cafe'
  get 'posts/sweets'
  get 'posts/nature'
  get 'posts/themepark'

  get 'tags/:tag', to: 'posts#index', as: :tag #追加

  get "posts/show/:id" => "posts#show"
  delete 'posts/show/:id' => 'posts#destroy'

  get 'users/show/:id' => 'users#show'

  root "pages#home"

  resources :posts,          only: [:create, :show, :destroy] do
    resources :likes, only: [:create, :destroy]
  end

  resources :posts do
    resources :comments, only: [:create, :destroy]
  end

  resources :users do
    member do
     get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>KOISPO</title>
        <%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    </head>


    <body>
  <header>

  <!-- ヘッダー  -->
  <% if user_signed_in? %>
<% else %>
<div class="easy-login d-flex justify-content-center align-items-center">
<%= link_to 'こちらからログインなしで利用できます', users_guest_sign_in_path, method: :post, style: "color:white;" %>
</div>
<% end %>
<nav class="navbar navbar-expand navbar-light mb-3">
  <div class="container">
    <!-- タイトル -->
    <div class="koispo">
<%= link_to image_tag("/images/Mustard Black Minimalist Etsy Shop Icon (4).png", size:'88x67', alt: "恋スポ"), root_path %>
</div>
      <!-- ユーザー一覧 -->
      <div class="header-user">
      <%= link_to users_index_path, class: "navbar-users nav-item nav-link active px-0 mr-1" do %>
        <i class="fas fa-user-friends" style="font-size: 1.7rem; position: relative; top: 1.5px; left: 16px; color: #555555;"></i>
        <% end %>
</div>
        <div class="collapse navbar-collapse justify-content-end">

        <ul class="navbar-nav align-items-center">

         <% if user_signed_in? %>
          <li class="nav-item d-flex align-items-center">

            <!--テスト-->
          <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle user-names" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          @<%= current_user.username %>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">

          <%= link_to 'マイページ', "/users/show/#{current_user.id}", class: "dropdown-item", style: "font-weight: 700;" %>

          <a href="/users/edit" class="dropdown-item">編集</a>
          <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "dropdown-item" %>
      </li>
          <!--/テスト-->

            <!-- アバター -->
            <% if current_user.avatar_id.present? %>
              <%=link_to (image_tag attachment_url(current_user, :avatar, :fill, 70, 70, format: "jpg"), class: 'head-userimg'),user_path(current_user) %>
                <% else %>
              <%=link_to (image_tag('/images/user-default.png', size: '70x70', class: 'head-userimg')), user_path(current_user) %>
            <% end %>

          </li>
          <li class="nav-item">

          <!-- 投稿 -->
            <%= link_to new_post_path, class: "btn btn-dark nav-btn", style: "background-color: #23272b; position: relative; left: 1px;" do %><i class="far fa-edit mr-1"></i>投稿<% end %>
          </li>

        <% else %>
          <li class="nav-item">

          <!-- ログイン -->
            <%= link_to "ログイン", new_user_session_path, class: "nav-link active px-0 mr-sm-2" %>
          </li>
          <li class="nav-item">

          <!-- 新規登録 -->
            <%= link_to "新規登録", new_user_registration_path, class: "btn btn-white nav-btn", style: "color:black;" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
<!-- /ヘッダー -->



        </header>

        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>

        <%= yield %>






  </body>



  <footer class="text-muted">
  <div class="copyright">
  <small>Copyright ©2020 KOISPO, All Rights Reserved.</small>
  </div>
</footer>


<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
      <script>window.jQuery || document.write('<script src="/docs/4.4/assets/js/vendor/jquery.slim.min.js"><\/script>')</script><script src="/docs/4.4/dist/js/bootstrap.bundle.min.js" integrity="sha384-6khuMg9gaYr5AxOqhkVIODVIvm9ynTT5J4V1cfthmT+emCG6yVmEZsRHdxlotUnm" crossorigin="anonymous"></script></body>
</html>